version: '3'

services:
  db_app:
    image: eduardovillasboas/db-mysql-app:latest
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: db_app
    restart: always
    tty: true
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

  node_app:
    image: eduardovillasboas/node-fullcycle-challenge
    container_name: node_app
    build:
      context: ./node 
      dockerfile: Dockerfile
    volumes:
      - ./node/src:/usr/app/src
    depends_on:
      - db_app
    networks:
      - node_network
    tty: true
    entrypoint: wait-for db_app:3306 -t 40  -- node .
    
  nginx_app:
    image: eduardovillasboas/nginx-fullcycle-challenge
    container_name: nginx_app
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    tty: true
    networks:
      - node_network
    ports:
      - "8080:80"
    
networks:
  node_network:
    name: node_network
    driver: bridge
    

